@startuml

class CDescriptor {
    const SIP_UI8 * & m_pui8Data
    GetTag()
    GetLength()
    GetTotalLength()
    GetData()
}

class CDescriptorList {
    GetTotalLength()
    InitList()
    GetDescriptorPtr()
}

class CData {
    const SIP_UI8 * m_pui8Data
    SIP_UI32        m_ui32DataLen
    SetData()
    GetLen()
    GetData()
    HexDump()
}

CData <|-- CPrivateSection


CPrivateSection <|-- CSectionPat

CPrivateSection <|-- CSectionPmt

CPrivateSection <|-- CSectionCat

CPrivateSection <|-- CSectionNit

CPrivateSection <|-- CSectionEcm

CPrivateSection <|-- CSectionEmm

@enduml