@startuml

class CDescriptor {
    const SIP_UI8 * & m_pui8Data
    GetTag()
    GetLength()
    GetTotalLength()
    GetData()
}

class CDescriptorList {
    const SIP_UI8 * & m_pui8Data
    SIP_UI16          m_ui16DescListLen
    GetTotalLength()
    InitList()
    GetDescriptorPtr()
}

class CData {
    const SIP_UI8 * m_pui8Data
    SIP_UI32        m_ui32DataLen
    SetData()
    GetLen()
    GetData()
    HexDump()
}

class CPrivateSection {
    SIP_UI8 GetTableID()
    SIP_UI8 GetSSI()
    SIP_UI16 GetSectionLegnth()
    SIP_UI16 GetTableIdExtension()
    SIP_UI8 GetVersionNo()
    SIP_UI8 GetCNI()
    SIP_UI8 GetSectionNumber()
    SIP_UI8 GetLastSectionNumber()
    const SIP_UI8* GetDescriptorList()
    const SIP_UI8* GetPrivateData()
    SIP_UI16 GetPrivateDataLength()
    SIP_UI32 GetSectionCRC()
    SIP_UI32 GetCalculatedCRC()
    SIP_UI32 GetFullDataCRC()
    bool ValidateCRC()
    bool isSectionValid()
    void PrintSectionInfo()
}

CData <|-- CPrivateSection


CPrivateSection <|-- CPatSection

CPrivateSection <|-- CPmtSection

CPrivateSection <|-- CCatSection

CPrivateSection <|-- CNitSection

CPrivateSection <|-- CEcmSection

CPrivateSection <|-- CEmmSection

@enduml